apiVersion: v1
kind: Secret
metadata:
  name: zero-trust-secrets
  namespace: zero-trust-system
type: Opaque
stringData:
  JWT_SECRET_KEY: "prod-zero-trust-pep-hmac-sha256-cryptographic-master-key-2026"
